### ISSUE TITLE
Reload input can jam launcher if there is no ammo in crates.

### ISSUE THREAD

**Issue by Uberdude9001** [TwistedTail/ACF-3-Missiles#10]
Steps to reproduce:

1. spawn multi-shot rack
2. spawn ammo crate
3. Fire until ammo crate is empty but rack still has ammo
4. Trigger reload input

The rack will now be "jammed" on an infinite reloading cycle until reload input is released.

**Comment by TwistedTail** [comment]
As of 72d3333, this is not longer an issue.
