### ISSUE TITLE
Missile HEAT does not lose penetration power after hitting props.

### ISSUE THREAD

**Issue by LeninCat** [TwistedTail/ACF-3-Missiles#11]
HEAT Jet from missiles is not losing any penetrative power after going through props . as shown below 
![image](https://user-images.githubusercontent.com/7826383/90977696-de346280-e579-11ea-8780-b061dc4e2d6a.png)
Each of these plates are 500mm and have exactly same amount of damage on each of them
![image](https://user-images.githubusercontent.com/7826383/90977711-f4dab980-e579-11ea-9bdb-77f305da356c.png)
![image](https://user-images.githubusercontent.com/7826383/90977718-002de500-e57a-11ea-9e8e-ed9533d7240b.png)
![image](https://user-images.githubusercontent.com/7826383/90977743-39665500-e57a-11ea-831b-f61d7512790b.png)

**Comment by TwistedTail** [comment]
Fixed on 0db9428.
