### ISSUE TITLE
Targetting radar breaks with targets owned by world

### ISSUE THREAD

**Issue by MonkaSC** [TwistedTail/ACF-3-Missiles#15]
Radar unit errors and stops functioning when it tries to pick up a target owned by nobody.

```
[ERROR] addons/acf3-missiles/lua/entities/acf_radar/init.lua:138: attempt to index a nil value
  1. unknown - addons/acf3-missiles/lua/entities/acf_radar/init.lua:138

Timer Failed! [ACF Radar Scan 226][@addons/acf3-missiles/lua/entities/acf_radar/init.lua (line 184)]
```
`
Own[Count] = Ent:CPPIGetOwner():GetName() or ""
`

**Comment by TwistedTail** [comment]
Should be addressed by c72160e on the dev branch, it's gonna be tested for a few days before it makes it to master. If you do use the dev branch and this problem persists then make sure the server has is using any CPPI-compliant prop protection addon.
