### ISSUE TITLE
[BUG] GLATGMs don't properly inherit the velocity of the gun firing them

### ISSUE THREAD

**Issue by CheezusChrust** [TwistedTail/ACF-3-Missiles#18]
When firing GLATGMs while driving forwards with the gun pointing straight, fired GLATGMs will collide with the gun (or the tank's turret depending on velocity) with hilarious consequences. See: https://streamable.com/9fvsdv

**Comment by TwistedTail** [comment]
Fixed on 4000686, merged to master on c858925. GLATGMs should no longer hit the weapon that fired them.
