### ISSUE TITLE
[Suggestion] Revert/Change Missile Rack Link Distance

### ISSUE THREAD

**Issue by bluemetaknight** [TwistedTail/ACF-3-Missiles#21]
With the menu update shortening link distance, a bunch of my builds have impacted. The ammo link changes I find to be acceptable, but radar to rack link distance is just excessively short. I don't know what the original link distance was, but somewhere around 450-500 units mass center to mass center would be plenty to allow for radar to link with missile racks on the wingtips of aircraft. Putting my radar in the center of my builds just seems kind of silly.

**Comment by TwistedTail** [comment]
Fixed on a098f6b. Entities were using the `ACF.RefillDistance` variable to define the maximum linking distance, which was lowered to about 300 inches. Now they're using the `ACF.LinkDistance` global, giving them a maximum linking distance of 650 inches.
