### ISSUE TITLE
Quad & Twin Missile/Bomb Racks Cannot be Interreacted With.

### ISSUE THREAD

**Issue by bluemetaknight** [TwistedTail/ACF-3-Missiles#29]
Quad and Twin racks cannot be moved using physics gun. They cannot be linked, and they cannot be removed using the undo key. You have to manually remove them using the context menu. This was on the official ACF3 build servers for context. No errors were spotted in my console, but who knows about server side.

**Comment by TwistedTail** [comment]
This was related to some assets that were removed by accident, which was fixed on https://github.com/Stooberton/ACF-3/commit/14edcc17d10150dc4a9dec5d94577a389a37c357. The servers are probably not using the latest version of ACF.
