### ISSUE TITLE
Kornet tube wont load missile

### ISSUE THREAD

**Issue by PolySteam** [TwistedTail/ACF-3-Missiles#3]
Kornet wont load a missile, probably has to do with the model missing an attachment point for the missile.

**Comment by TwistedTail** [comment]
Yeah, noticed they even left a comment about it being "a hack". I don't have any experience with modelling so I haven't fixed it myself.

**Comment by PolySteam** [comment]
Can probably just use attachment 0 if it doesnt find any other attachment.

**Comment by TwistedTail** [comment]
Fixed on 94594c2.
