### ISSUE TITLE
[BUG] GLATGMs freeze mid-air when laser guided

### ISSUE THREAD

**Issue by Tox00** [TwistedTail/ACF-3-Missiles#38]
**Short Description**

When using a laser guidance computer to guide GLATGMs the GLATGMs will freeze shortly after being fired.

**Console Error Logs**

None at all.

**How to Reproduce (Optional)**

Link a GLATGM firing gun and link it to a laser guidance computer and start lasing.

**Screenshots**

https://youtu.be/zUw5DOsxvCg

**Comment by TwistedTail** [comment]
It should be addressed by #39. You're free to close the issue if that's the case.
