### ISSUE TITLE
Folding-Fin Aerial Rockets Error

### ISSUE THREAD

**Issue by ShadowzOfTheDark** [TwistedTail/ACF-3-Missiles#50]
Using the 57mm or 80mm Pod Rocket causes the following error:

```
[acf3] addons/acf3/lua/acf/base/sh_round_functions.lua:67: bad argument #1 to 'min' (number expected, got nil)
  1. min - [C]:-1
   2. RoundBaseGunpowder - addons/acf3/lua/acf/base/sh_round_functions.lua:67
    3. BaseConvert - addons/acf3/lua/acf/shared/ammo_types/he.lua:53
     4. ClientConvert - addons/acf3/lua/acf/shared/ammo_types/ap.lua:177
      5. UpdateAmmoMenu - addons/acf3/lua/acf/client/ammo_menu.lua:196
       6. OnSelect - addons/acf3-missiles/lua/acf/client/menu_items/missiles_menu.lua:120
        7. ChooseOption - lua/vgui/dcombobox.lua:99
         8. DoClick - lua/vgui/dcombobox.lua:213
          9. OnMouseReleased - lua/vgui/dlabel.lua:237
           10. unknown - lua/vgui/dmenuoption.lua:76
```

This prevents you from spawning and using those weapons. 

Looking at [https://github.com/TwistedTail/ACF-3-Missiles/blob/master/lua/acf/shared/missiles/ffar.lua](url) briefly shows that the 57mm and 80mm Pod Rockets have duplicate entries, could this be the cause? If so which one to keep?

**Comment by ShadowzOfTheDark** [comment]
Can confirm that the duplicate entries is the cause of the error. It's just a matter of deciding which entry is the one we want to use.

**Comment by TwistedTail** [comment]
Seems to be a merging issue. I'll look into it right away.
