### ISSUE TITLE
guidance

### ISSUE THREAD

**Issue by DoomMarine91** [TwistedTail/ACF-3-Missiles#51]
missile guidance for this addon has to be either badly done or non existant as there is no way to make missiles steer to target not from the rack or anything. 

please explain

**Comment by CheezusChrust** [comment]
[Have you looked at the guidance modes here?](https://github.com/Stooberton/ACF-3/wiki/Guidance-Modes)

**Comment by TwistedTail** [comment]
Like @CheezusChrust said, guidance has been changed entirely on ACF-3. Most guidance modes require a guidance computer, you can also find a list of these on the wiki, linked to the firing rack. On that wiki article he posted you can find a rough explanation of how to get each guidance to work properly. It goes without saying, you should also make sure your missiles are not set to Dumb  guidance.
