### ISSUE TITLE
[BUG] Missile racks not recognized with ACF Sound Replacer  

### ISSUE THREAD

**Issue by luftehJSF** [TwistedTail/ACF-3-Missiles#6]
I recently tried replacing the sounds on my missile racks normally on one of my contraptions. Noticing when clicking the racks with the sound replacer (loaded and not loaded with missiles), I get the notification "Only Acf entities are supported by the ACF sound tool". 
![20200612003745_2](https://user-images.githubusercontent.com/43308167/84465732-c79e9080-ac45-11ea-9f01-5f3a160343e5.jpg)
 Sometimes when clicking on the rack with the sound replacer, the notification will not appear, but the missile rack will not have the replaced sound on it. 
https://streamable.com/5ngrb5

**Comment by TwistedTail** [comment]
It was something else. Missiles were fired before the custom firing sound was set on their bulletdata, so they'd always use their default fire sound instead. Fixed on bca16e9.
