### ISSUE TITLE
[Bug] In flight Rocket/Missiles/Bombs take no damage.

### ISSUE THREAD

**Issue by LeninCat** [TwistedTail/ACF-3-Missiles#61]
Rocket/Missiles/Bombs in flight take no damage from any ACF weapons.

TOW taking multiple hits from 4x 40mm autocannon without any damage registered
![image](https://user-images.githubusercontent.com/7826383/160987089-673797bd-f66f-42aa-8e16-bb7a9341fb27.png)
(cannon with accuarcy set to 0.0005 for testing).

Version
Missiles DEV [d7899de](https://github.com/TwistedTail/ACF-3-Missiles/commit/d7899de190781cfde28f61ca5b5ca83781465f7a)
Base DEV [72f2190](https://github.com/Stooberton/ACF-3/commit/72f2190d4b49024a4e953cc0ca2c2eb49a509469)

**Comment by TwistedTail** [comment]
Bullets seem to be detecting missiles as a "world" type entity.
![image](https://user-images.githubusercontent.com/8784231/161398481-bcbee31d-4fef-4592-88a6-c10dc739e321.png)

**Comment by TwistedTail** [comment]
Fixed on 2d9ecf3.
