### ISSUE TITLE
Infrared missile errors out

### ISSUE THREAD

**Issue by Eye29** [TwistedTail/ACF-3-Missiles#73]
All of the other missile types work fine and other weapons like cannons but the infrared errors out when trying to fire it and it just floats around in the world.
ACF3 and 3missiles installed with GitClient
Mod list
Wiremod
Nadmod Prop Protection

Error message 
[acf-3-missiles] addons/acf-3-missiles/lua/acf/entities/countermeasure/globals.lua:155: attempt to index local 'CounterMeasure' (a function value)
  1. ACFM_ApplySpawnCountermeasures - addons/acf-3-missiles/lua/acf/entities/countermeasure/globals.lua:155
   2. PreGuidance - addons/acf-3-missiles/lua/acf/entities/guidance/dumb.lua:21
    3. GetGuidance - addons/acf-3-missiles/lua/acf/entities/guidance/infrared.lua:44
     4. CalcFlight - addons/acf-3-missiles/lua/entities/acf_missile/init.lua:186
      5. unknown - addons/acf-3-missiles/lua/entities/acf_missile/init.lua:632 (x7)
https://youtu.be/JwiOsE5XVc8

**Comment by TwistedTail** [comment]
Fixed on ae206cc.
